import { a } from "@aws-amplify/backend";

export const tablesWithDeleteProtection = [
  "ProjectActivity",
  "NoteBlockPerson",
  "NoteBlock",
  "Todo",
  "Activity",
];

const activitySchema = {
  // ------- Enums
  TodoStatus: a.enum(["OPEN", "DONE"]),

  // ------- Models
  ProjectActivity: a
    .model({
      owner: a
        .string()
        .authorization((allow) => [allow.owner().to(["read", "delete"])]),
      // FKs
      activityId: a.id().required(),
      projectsId: a.id().required(),
      // relations
      activity: a.belongsTo("Activity", "activityId"),
      projects: a.belongsTo("Projects", "projectsId"),
      // Backfill marker. Set to "1" by the one-off snapshot backfill script on
      // junction rows whose Activity has no cached snapshot yet. The backfill
      // worker clears it after (re)generating the activity snapshot. Left
      // unset in normal operation, so the GSI below is SPARSE — it holds only
      // rows still awaiting a backfill. Sorted by projectsId so the enqueue
      // step walks the work project-by-project.
      snapshotPending: a.string(),
    })
    .secondaryIndexes((index) => [
      index("projectsId"),
      index("snapshotPending")
        .sortKeys(["projectsId"])
        .queryField("listSnapshotPending"),
    ])
    .authorization((allow) => [allow.owner()]),

  NoteBlockPerson: a
    .model({
      owner: a
        .string()
        .authorization((allow) => [allow.owner().to(["read", "delete"])]),
      createdAt: a.datetime().required(),
      // FKs
      personId: a.id().required(),
      noteBlockId: a.id().required(),
      // relations
      person: a.belongsTo("Person", "personId"),
      noteBlock: a.belongsTo("NoteBlock", "noteBlockId"),
    })
    .secondaryIndexes((index) => [
      index("personId").sortKeys(["createdAt"]).queryField("listByPersonId"),
    ])
    .authorization((allow) => [allow.owner()]),

  NoteBlock: a
    .model({
      owner: a
        .string()
        .authorization((allow) => [allow.owner().to(["read", "delete"])]),
      content: a.json(),
      type: a.string().required(),
      formatVersion: a.integer().required(),
      // AI-generated description of the image for `s3image` blocks. Written by
      // the image-description Lambda (Bedrock vision), read by the export
      // markdown renderer. Null for non-image blocks.
      imageDescription: a.string(),
      imageDescriptionUpdatedAt: a.datetime(),
      // Backfill marker. Set to "1" by the one-off image-description backfill
      // script on existing `s3image` blocks that lack a description. The
      // backfill worker clears it once the description is generated. Left
      // unset in normal operation, so the GSI below is SPARSE — it contains
      // only blocks still awaiting a backfilled description.
      imageDescriptionPending: a.string(),
      // FKs
      activityId: a.id().required(),
      todoId: a.id(),
      // relations
      activity: a.belongsTo("Activity", "activityId"),
      todo: a.belongsTo("Todo", "todoId"),
      people: a.hasMany("NoteBlockPerson", "noteBlockId"),
    })
    .secondaryIndexes((index) => [
      index("type"),
      // Sparse work-queue index for the image-description backfill.
      index("imageDescriptionPending").queryField(
        "listImageDescriptionPending"
      ),
    ])
    .authorization((allow) => [allow.owner()]),

  Todo: a
    .model({
      owner: a
        .string()
        .authorization((allow) => [allow.owner().to(["read", "delete"])]),
      todo: a.json().required(),
      status: a.ref("TodoStatus").required(),
      doneOn: a.date(),
      // relations
      activity: a.hasOne("NoteBlock", "todoId"),
      dailyTodos: a.hasMany("DailyPlanTodo", "todoId"),
    })
    .secondaryIndexes((index) => [index("status")])
    .authorization((allow) => [allow.owner()]),

  Activity: a
    .model({
      owner: a
        .string()
        .authorization((allow) => [allow.owner().to(["read", "delete"])]),
      name: a.string(),
      notionId: a.integer(),
      formatVersion: a.integer().default(1),
      finishedOn: a.datetime(),
      notes: a.string(), // DEPRECATED
      notesJson: a.json(), // DEPRECATED
      // Cached markdown snapshot of this activity's note blocks. Regenerated
      // by the snapshot Lambda ~5 min after the last note-block change
      // (trailing debounce). "Export for AI" reads this instead of rendering
      // on the fly. May be null/empty when notes were just created.
      notesMarkdown: a.string(),
      notesMarkdownUpdatedAt: a.datetime(),
      // Cached, context-free header for this activity (no leading '#'; the
      // export routines add the heading level). Regenerated by the snapshot
      // Lambda on the same 5-min debounce. Two cases:
      //  - activity belongs to a meeting  -> "Topic: <project name>, <…>"
      //  - standalone note (no meeting)   -> the activity date in the same
      //    format as the meeting header ("YYYY-MM-DD HH:mm CET").
      activityHeaderMarkdown: a.string(),
      activityHeaderMarkdownUpdatedAt: a.datetime(),
      // FKs
      meetingActivitiesId: a.id(),
      noteBlockIds: a.string().required().array(),
      // relations
      forProjects: a.hasMany("ProjectActivity", "activityId"),
      forMeeting: a.belongsTo("Meeting", "meetingActivitiesId"),
      noteBlocks: a.hasMany("NoteBlock", "activityId"),
    })
    .authorization((allow) => [allow.owner()]),
};

export default activitySchema;
